### ISSUE TITLE
Where should we contribute exercises to for the lecture videos?

### ISSUE THREAD

**Issue by WizardOfAus** [cryptoeconomics-study/code#1]
Where should we contribute exercises to for the lecture videos in this repo:

E.g. for the exercise box displayed:

<img width="841" alt="screen shot 2018-07-20 at 9 16 14 am" src="https://user-images.githubusercontent.com/9751831/42991481-93e1bc6e-8bfd-11e8-811b-8c05df7967b6.png">

**Comment by karlfloersch** [comment]
Ah! Great question! The exercise code is located here: https://github.com/cryptoeconomics-study/website/blob/master/lectures/chapter-01-0.md 

It uses a Gitbook plugin & so you just have to follow the format they provide. It would be nice if there were other types of exercises / practice problems like multiple choice, but that would require some gitbook hacking which I haven't had time for just yet

**Comment by WizardOfAus** [comment]
Cool! Will push a multiple choice plugin and some sample exercises
